blank_issues_enabled: true
contact_links:
  - name: "💬 Discussions"
    url: https://github.com/GeOsmFamily/geosm-frontend-refactor/discussions
    about: "Posez vos questions ou partagez vos idées dans les discussions."
